apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "components.oda.tmforum.org"
spec:
  scope: "Namespaced"
  group: "oda.tmforum.org"
  names:
    plural: "components"
    singular: "component"
    kind: "component"
  versions: 
  - name: "v1alpha1"
    # Each version can be enabled/disabled by Served flag.
    served: true
    # One and only one version must be marked as the storage version.
    storage: false
    deprecated: true
    deprecationWarning: "oda.tmforum.org/v1alpha1 Component is deprecated; Please upgrade to oda.tmforum.org/v1alpha2 see https://github.com/tmforum-oda/oda-canvas-charts/issues/9"
    schema:
      openAPIV3Schema:
        type: object
        required: ["spec"]
        properties:
          spec:
            type: object               
            required: ["coreFunction"]
            properties:
              coreFunction:
                type: object              
                required: ["coreFunction", "eventNotification", "management", "security"]
                properties:
                  exposedAPIs: 
                    type: array                
                    items:
                      type: object
                  dependantAPIs: 
                    type: array                
                    items:
                      type: object
              eventNotification:
                type: object  
                properties:
                  publishedEvents: 
                    type: array                
                    items:
                      type: object
                  subscribedEvents: 
                    type: array            
                    items:
                      type: object
              management:
                type: array                
                items:
                  type: object
              security:
                type: object
    additionalPrinterColumns:
    - name: exposed_APIs
      type: string
      description: list the endpoints for exposed APIs
      jsonPath: .status.exposedAPIsummary
    - name: developer_UI
      type: string
      description: list the Developer User Interface(s)
      jsonPath: .status.developerUIsummary
    - name: deployment_status
      type: string
      description: Deployment status [in progress, complete, failed]
      jsonPath: .status.deployment_status
  - name: "v1alpha2"
    # Each version can be enabled/disabled by Served flag.
    served: true
    # One and only one version must be marked as the storage version.
    storage: true
    deprecated: false
    schema:
      openAPIV3Schema:
        type: object
        required: ["spec"]
        properties:
          spec:
            type: object               
            required: ["coreFunction"]
            properties:
              coreFunction:
                type: object              
                required: ["coreFunction", "eventNotification", "management", "security"]
                properties:
                  exposedAPIs: 
                    type: array                
                    items:
                      type: object
                  dependantAPIs: 
                    type: array                
                    items:
                      type: object
              eventNotification:
                type: object  
                properties:
                  publishedEvents: 
                    type: array                
                    items:
                      type: object
                  subscribedEvents: 
                    type: array            
                    items:
                      type: object
              management:
                type: array                
                items:
                  type: object
              security:
                type: object
    additionalPrinterColumns:
    - name: exposed_APIs
      type: string
      description: list the endpoints for exposed APIs
      jsonPath: .status.exposedAPIsummary
    - name: developer_UI
      type: string
      description: list the Developer User Interface(s)
      jsonPath: .status.developerUIsummary
    - name: deployment_status
      type: string
      description: Deployment status [in progress, complete, failed]
      jsonPath: .status.deployment_status