{{- if or .Values.dbaas.enabled .Values.postgresql.enabled}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-kc-configmap
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  {{- if .Values.dbaas.enabled }}
  DB_VENDOR: {{ .Values.dbaas.vendor }}
  DB_ADDR: {{ .Values.dbaas.address }}
  DB_PORT: {{ .Values.dbaas.port | quote }}
  {{ else if .Values.postgresql.enabled }}
  DB_VENDOR: "postgres"
  DB_ADDR: {{ .Release.Name }}-postgresql.{{ .Release.Namespace }}
  DB_PORT: {{ .Values.dbaas.port | quote }}
  {{ end }}
{{ end }}