apiVersion: apps/v1
kind: Deployment
metadata:
  name: oda-controller-ingress
  namespace: {{.Values.global.namespaceCanvas.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oda-controller-ingress
  template:
    metadata:
      labels:
        app: oda-controller-ingress
    spec:
      serviceAccountName: odacomponent-account
      containers:
      - name: oda-controller-ingress
        image: {{.Values.deployment.image}}
        env:
        - name: LOGGING
          value: '20'           
        - name: COMPONENT_NAMESPACE
          value: {{.Values.deployment.monitorednamespaces}}
