---
apiVersion: zalando.org/v1
kind: ClusterKopfPeering
metadata:
  name: default
---
apiVersion: zalando.org/v1
kind: KopfPeering
metadata:
  namespace: {{.Values.global.namespaceCanvas.name}}
  name: default
---