{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "controller.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  KEYCLOAK_USER: {{ .Values.secret.user | b64enc | quote }}
  KEYCLOAK_PASSWORD: {{ .Values.secret.pass | b64enc | quote }}
{{ end }}