apiVersion: v1
kind: Service
metadata:
  name: seccon
  namespace: {{ .Release.Namespace }}
  labels:
    app: oda-controller-ingress #link service to Pod and not individual container
spec:
  ports:
  - port: 5000
    targetPort: seccon
    name: seccon
  type: NodePort
  selector:
    app: oda-controller-ingress