apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  keycloak_admin_user: {{ .Values.secret.user | b64enc | quote }}
  keycloak_admin_password: {{ .Values.secret.pass | b64enc | quote }}
  {{- if or .Values.dbaas.enabled .Values.postgresql.enabled }}
  postgres_db_user: {{ .Values.postgresql.postgresqlUsername | b64enc }}
  postgres_db_password: {{ .Values.postgresql.postgresqlPassword | b64enc }}
  {{ end }}