# Recursive 
# https://github.com/helm/helm/issues/2247
# https://github.com/Noksa/helm-resolve-deps
  # Default values for cert-manager-init.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.
global:
  certificate:
    appName: "compcrdwebhook"

oda-cdrs:
  enabled: true
canvas-namespaces:
  enabled: true
  certManagerNamespace: cert-manager
  componentNamespace: components
  istio:
    labelEnabledComponent: true
cert-manager-init:
  nameOverride: ""
  fullnameOverride: ""
  namespace: canvas
  # The certificate has a default duration of 90d. It rotates automatically, but the the server using it doesn't handle that rotation
  # https://github.com/tmforum-oda/oda-canvas-charts/issues/38
  #
  certificateDuration: 21600h
  #Cert manager get a lease  object on kube-system namespace to elect leader.
  #The time to wait for a leader is 60s. 
  #The lease can survive among instalations, so cainjectot can waits up to 60s to become leader
  #If cainjector is not fully initilizaded we can find the following error
  #  cert-manager-init/templates/issuer.yaml failed: Internal error occurred: 
  #  failed calling webhook "webhook.cert-manager.io": failed to call webhook: 
  #  Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": x509: certificate signed by unknown authority
  # In seconds
  leaseWaitTimeonStartup: 20

  cert-manager:
    enabled: true
    installCRDs: true
    namespace: cert-manager

keycloak:
  enabled: true
  auth:
    adminUser: "admin"
    adminPassword: "adpass"
  postgresql:
    enabled: true
    postgresqlUsername: "keycloak"
    postgresqlPassword: "keycloakdbuser"
    postgresqlDatabase: "keycloak"
  httpRelativePath: "/auth/"
  #proxy: edge
  #tls:
  #  enabled: true
  #  autoGenerated: true
  #extraEnvVars:
  #  - name: PROXY_ADDRESS_FORWARDING
  #    value: "true"
  ## @param containerPorts.http Keycloak HTTP container port
  ## @param containerPorts.https Keycloak HTTPS container port
  ##
  #containerPorts:
  #  http: 8080
  #  https: 8443
  #service:
  #  ports:
  #    http: 8080
  #Create a myrealm realm with a seccon user
  keycloakConfigCli:
    enabled: true
    backoffLimit: 1
    command: [ "java", "-jar", "/opt/keycloak-config-cli.jar" ]
    configuration:
      myrealm.json: |
        {
          "enabled": true,
          "realm": "myrealm",
          "users": [
            {
            "username": "seccon",
            "email": "seccon@oda.io",
            "enabled": true,
            "firstName": "Security",
            "lastName": "User"
            }
           ]
        }

  ingress:
    enabled: false
    ingressClassName: "traefik"
    hosts:
      - name: keycloak.local
        path: /
        tls: false
controller:
  deployment:
    controllerName: oda-controller-ingress
    compconImage: tmforumodacanvas/component-istio-controller:0.2.6
    istioGateway: true
    #gusjer/security-listener:0.7.0
    secconImage: tmforumodacanvas/security-listener:0.6.0
    monitoredNamespaces: 'components'           # comma separated list of namespaces
    ingressClass:
      enabled: false
      name: nginx
  #We reuse the admin user created on keycloak instalation
  credentials:
    user: admin
    pass: adpass
  configmap:
    kcrealm: myrealm
    loglevel: '20'
webhooks:
  image: tmforumodacanvas/compcrdwebhook:0.5.1