apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    {{- include "controller.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  LOGGING: {{ .Values.configmap.loglevel | quote }}
  KEYCLOAK_BASE: "http://{{ .Release.Name }}-keycloak.{{ .Release.Namespace }}:8088/auth"
  KEYCLOAK_REALM: {{ .Values.configmap.kcrealm }}
  COMPONENT_NAMESPACE: {{.Values.deployment.monitorednamespaces}}
  {{- if .Values.deployment.ingressClass.enabled }}
  INGRESS_CLASS: {{ .Values.deployment.ingressClass.name }}
  {{ end }}