{{- if .Values.global.namespaceDefault.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{.Values.global.namespaceDefault.name}}
  labels:
    {{- include "canvas.labels" . | nindent 4 }}
{{- end }}
