deployment:
  image: lesterthomas/odacomponentcontroller-ingress:latest
  monitorednamespaces: 'components'           # comma separated list of namespaces
  ingressClass:
    enabled: false
    name: nginx